package com.syspeak.makereap.system.security.entity;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.syspeak.modules.domain.model.identity.LongIdEntity;

/**
 * Attach .
 *
 * @author Lingo
 */
@Entity
@Table(name = "CMS_ATTACH")
public class Attach extends LongIdEntity {

	/** null. */
	private Content content;

	/** null. */
	private String name;

	/** null. */
	private String path;

	/** null. */
	private Date createTime;

	/** null. */
	private String descn;

	public Attach() {
	}

	public Attach(Content content, String name, String path, Date createTime, String descn) {
		this.content = content;
		this.name = name;
		this.path = path;
		this.createTime = createTime;
		this.descn = descn;
	}

	/** @return null. */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTENT_ID")
	public Content getContent() {
		return this.content;
	}

	/** @param content null. */
	public void setContent(Content content) {
		this.content = content;
	}

	/** @return null. */
	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	/** @param name null. */
	public void setName(String name) {
		this.name = name;
	}

	/** @return null. */
	@Column(name = "PATH", length = 200)
	public String getPath() {
		return this.path;
	}

	/** @param path null. */
	public void setPath(String path) {
		this.path = path;
	}

	/** @return null. */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 6)
	public Date getCreateTime() {
		return this.createTime;
	}

	/** @param createTime null. */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/** @return null. */
	@Column(name = "DESCN", length = 200)
	public String getDescn() {
		return this.descn;
	}

	/** @param descn null. */
	public void setDescn(String descn) {
		this.descn = descn;
	}
}
