package com.syspeak.itboss.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attach .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "CMS_ATTACH")
public class Attach {

	private static final long serialVersionUID = 97313830394506621L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	private Content content;

	@Column(name = "NAME", length = 50)
	private String name;

	@Column(name = "PATH", length = 200)
	private String path;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 6)
	private Date createTime;

	@Column(name = "DESCN", length = 200)
	private String descn;

	public Attach() {
	}

	public Attach(Content content, String name, String path, Date createTime,
			String descn) {
		this.content = content;
		this.name = name;
		this.path = path;
		this.createTime = createTime;
		this.descn = descn;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}
}
