package com.syspeak.itboss.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Content .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "CMS_CONTENT")
public class Content {

	private static final long serialVersionUID = 8805919087096311763L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	private Category category;

	@Column(name = "TITLE", length = 50)
	private String title;

	@Column(name = "STATUS")
	private Integer status;

	@Column(name = "CREATOR", length = 50)
	private String creator;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 6)
	private Date createTime;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 6)
	private Date updateTime;

	@Column(name = "CONTENT", length = 2000)
	private String content;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "content")
	private Set<Attach> attachs = new HashSet<Attach>(0);

	public Content() {
	}

	public Content(Category category, String title, Integer status,
			String creator, Date createTime, Date updateTime, String content,
			Set<Attach> attachs) {
		this.category = category;
		this.title = title;
		this.status = status;
		this.creator = creator;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.content = content;
		this.attachs = attachs;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Set<Attach> getAttachs() {
		return this.attachs;
	}

	public void setAttachs(Set<Attach> attachs) {
		this.attachs = attachs;
	}
}
