package com.syspeak.itboss.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Resc .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "SEC_RESC")
public class Resc {

	private static final long serialVersionUID = -6012046672697187060L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	private Group group;

	@Column(name = "RES_TYPE", nullable = false, length = 100)
	private String resType;

	@Column(name = "RES_STRING", nullable = false, length = 200)
	private String resString;

	@Column(name = "CREATOR", nullable = false, length = 50)
	private String creator;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 6)
	private Date createTime;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 6)
	private Date updateTime;

	@Column(name = "STATUS", nullable = false)
	private int status;

	@Column(name = "PRIORITY", nullable = false)
	private int priority;

	@Column(name = "DESCN", length = 200)
	private String descn;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SEC_GROUP_RESC", schema = "PUBLIC", joinColumns = { @JoinColumn(name = "RESC_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "GROUP_ID", nullable = false, updatable = false) })
	private Set<Group> groups = new HashSet<Group>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SEC_ROLE_RESC", schema = "PUBLIC", joinColumns = { @JoinColumn(name = "RESC_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) })
	private Set<Role> roles = new HashSet<Role>(0);

	public Resc() {
	}

	public Resc(Group group, String resType, String resString, String creator,
			Date createTime, int status, int priority) {
		this.group = group;
		this.resType = resType;
		this.resString = resString;
		this.creator = creator;
		this.createTime = createTime;
		this.status = status;
		this.priority = priority;
	}

	public Resc(Group group, String resType, String resString, String creator,
			Date createTime, Date updateTime, int status, int priority,
			String descn, Set<Group> groups, Set<Role> roles) {
		this.group = group;
		this.resType = resType;
		this.resString = resString;
		this.creator = creator;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.status = status;
		this.priority = priority;
		this.descn = descn;
		this.groups = groups;
		this.roles = roles;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public String getResType() {
		return this.resType;
	}

	public void setResType(String resType) {
		this.resType = resType;
	}

	public String getResString() {
		return this.resString;
	}

	public void setResString(String resString) {
		this.resString = resString;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}
}
