package com.syspeak.itboss.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.StringUtils;

import com.syspeak.modules.domain.model.identity.LongIdEntity;

/**
 * Role .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "SEC_ROLE")
public class Role extends LongIdEntity {

	private static final long serialVersionUID = -1169790838142991071L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	private Group group;

	@Column(name = "NAME", nullable = false, length = 50)
	private String name;

	@Column(name = "CREATOR", nullable = false, length = 50)
	private String creator;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 6)
	private Date createTime;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 6)
	private Date updateTime;

	@Column(name = "STATUS", nullable = false)
	private int status;

	@Column(name = "LOGO", nullable = false, length = 200)
	private String logo;

	@Column(name = "DESCN", length = 200)
	private String descn;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SEC_USER_ROLE", schema = "PUBLIC", joinColumns = { @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "USER_ID", nullable = false, updatable = false) })
	private Set<User> users = new HashSet<User>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SEC_GROUP_ROLE", schema = "PUBLIC", joinColumns = { @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "GROUP_ID", nullable = false, updatable = false) })
	private Set<Group> groups = new HashSet<Group>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SEC_ROLE_RESC", schema = "PUBLIC", joinColumns = { @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "RESC_ID", nullable = false, updatable = false) })
	private Set<Resc> rescs = new HashSet<Resc>(0);

	public Role() {
	}

	public Role(Group group, String name, String creator, Date createTime,
			int status, String logo) {
		this.group = group;
		this.name = name;
		this.creator = creator;
		this.createTime = createTime;
		this.status = status;
		this.logo = logo;
	}

	public Role(Group group, String name, String creator, Date createTime,
			Date updateTime, int status, String logo, String descn,
			Set<User> users, Set<Group> groups, Set<Resc> rescs) {
		this.group = group;
		this.name = name;
		this.creator = creator;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.status = status;
		this.logo = logo;
		this.descn = descn;
		this.users = users;
		this.groups = groups;
		this.rescs = rescs;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Group getGroup() {
		return group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public String getDescn() {
		return descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<Group> getGroups() {
		return groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

	public Set<Resc> getRescs() {
		return rescs;
	}

	public void setRescs(Set<Resc> rescs) {
		this.rescs = rescs;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Set<String> getRescPermissions() {
		Set<String> permissions = new LinkedHashSet<String>();
		for (Resc resc : rescs) {
			String permission = resc.getResString();
			if (StringUtils.isBlank(permission)) {
				continue;
			}
			permissions.add(permission);
		}
		return permissions;
	}
}
